defaults:
  adapter: postgresql
  database: "<%=ENV['OPENSHIFT_APP_NAME']%>"
  encoding: utf8
  host: "<%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>"
  min_messages: ERROR
  password: "<%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>"
  pool: 5
  port: "<%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>"
  reconnect: false
  timeout: 5000
  username: "<%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>"
development:
  adapter: postgresql
  database: "<%=ENV['OPENSHIFT_APP_NAME']%>"
  encoding: utf8
  host: "<%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>"
  min_messages: ERROR
  password: "<%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>"
  pool: 5
  port: "<%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>"
  reconnect: false
  timeout: 5000
  username: "<%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>"
production:
  adapter: postgresql
  database: "<%=ENV['OPENSHIFT_APP_NAME']%>"
  encoding: utf8
  host: "<%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>"
  min_messages: ERROR
  password: "<%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>"
  pool: 5
  port: "<%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>"
  reconnect: false
  timeout: 5000
  username: "<%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>"
test:
  adapter: postgresql
  database: "<%=ENV['OPENSHIFT_APP_NAME']%>"
  encoding: utf8
  host: "<%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>"
  min_messages: ERROR
  password: "<%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>"
  pool: 5
  port: "<%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>"
  reconnect: false
  timeout: 5000
  username: "<%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>"
