production:
  host: <%= ENV['DB_HOST'] %>
  adapter: <%= ENV['DB_ADAPTER'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  port: <%= ENV['DB_PORT'] %>
  pool: <%= ENV['DB_POOL'] %>
  timeout: <%= ENV['DB_TIMEOUT'] %>
